module.exports = {
  italianSpiderman: {
    data: {
      Title: 'Italian Spiderman',
      Year: '2007',
      Rated: 'N/A',
      Released: '08 Nov 2007',
      Runtime: '40 min',
      Genre: 'Short, Action, Comedy',
      Director: 'Dario Russo',
      Writer: 'Dario Russo, David Ashby, Tait Wilson, Will Spartalis, Boris Repasky',
      Actors: 'David Ashby, Chris Asimos, Anna Cashman, Michael Crisci',
      Plot: 'When an otherworldly substance with amazing cloning properties falls into the hands of the evil criminal mastermind, Captain Maximum, only the extreme powers of the Italian Spiderman can save the world.',
      Language: 'English, Italian',
      Country: 'Australia',
      Awards: 'N/A',
      Poster: 'https://m.media-amazon.com/images/M/MV5BYjFhN2RjZTctMzA2Ni00NzE2LWJmYjMtNDAyYTllOTkyMmY3XkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_SX300.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.0/10' }],
      Metascore: 'N/A',
      imdbRating: '8.0',
      imdbVotes: '842',
      imdbID: 'tt2705436',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True'
    }
  },
  bond: {
    data: {
      Title: 'James Bond',
      Year: '2007',
      Rated: 'N/A',
      Released: '08 Nov 2007',
      Runtime: '40 min',
      Genre: 'Short, Action, Comedy',
      Director: 'Dario Russo',
      Writer: 'Dario Russo, David Ashby, Tait Wilson, Will Spartalis, Boris Repasky',
      Actors: 'David Ashby, Chris Asimos, Anna Cashman, Michael Crisci',
      Plot: 'When an otherworldly substance with amazing cloning properties falls into the hands of the evil criminal mastermind, Captain Maximum, only the extreme powers of the Italian Spiderman can save the world.',
      Language: 'English, Italian',
      Country: 'Australia',
      Awards: 'N/A',
      Poster: 'https://m.media-amazon.com/images/M/MV5BYjFhN2RjZTctMzA2Ni00NzE2LWJmYjMtNDAyYTllOTkyMmY3XkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_SX300.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.0/10' }],
      Metascore: 'N/A',
      imdbRating: '8.0',
      imdbVotes: '842',
      imdbID: 'tt2705436',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True'
    }
  },
  scary: {
    data: {
      Title: 'Scary Movie 4',
      Year: '2007',
      Rated: 'N/A',
      Released: '08 Nov 2007',
      Runtime: '40 min',
      Genre: 'Short, Action, Comedy',
      Director: 'Dario Russo',
      Writer: 'Dario Russo, David Ashby, Tait Wilson, Will Spartalis, Boris Repasky',
      Actors: 'David Ashby, Chris Asimos, Anna Cashman, Michael Crisci',
      Plot: 'When an otherworldly substance with amazing cloning properties falls into the hands of the evil criminal mastermind, Captain Maximum, only the extreme powers of the Italian Spiderman can save the world.',
      Language: 'English, Italian',
      Country: 'Australia',
      Awards: 'N/A',
      Poster: 'https://m.media-amazon.com/images/M/MV5BYjFhN2RjZTctMzA2Ni00NzE2LWJmYjMtNDAyYTllOTkyMmY3XkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_SX300.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.0/10' }],
      Metascore: 'N/A',
      imdbRating: '8.0',
      imdbVotes: '842',
      imdbID: 'tt2705436',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True'
    }
  }
}
